"""initial schema

Revision ID: b38b26953e61
Revises: 
Create Date: 2026-08-09 12:47:04.906339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38b26953e61'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('aws_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_alias', sa.String(length=255), nullable=False),
    sa.Column('aws_account_id', sa.String(length=12), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('auth_method', sa.Enum('ASSUME_ROLE', 'ACCESS_KEY', name='awsauthmethod'), nullable=False),
    sa.Column('role_arn', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('encrypted_access_key_id', sa.String(length=512), nullable=True),
    sa.Column('encrypted_secret_access_key', sa.String(length=512), nullable=True),
    sa.Column('validation_status', sa.Enum('PENDING', 'VALID', 'INVALID', name='accountvalidationstatus'), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aws_accounts_user_id'), 'aws_accounts', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('groq_model_override', sa.String(length=128), nullable=True),
    sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('critical_finding_alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('audit_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aws_account_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', name='auditstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resources_scanned', sa.Integer(), nullable=False),
    sa.Column('security_score', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aws_account_id'], ['aws_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_sessions_aws_account_id'), 'audit_sessions', ['aws_account_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('audit_session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='chatrole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_session_id'], ['audit_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_messages_audit_session_id'), 'ai_messages', ['audit_session_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_user_id'), 'ai_messages', ['user_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_session_id', sa.String(length=36), nullable=False),
    sa.Column('service', sa.Enum('IAM', 'S3', 'EC2', 'CLOUDTRAIL', 'CLOUDWATCH', 'LAMBDA', 'RDS', 'KMS', 'SECRETS_MANAGER', name='awsservice'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFORMATIONAL', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'SUPPRESSED', name='findingstatus'), nullable=False),
    sa.Column('resource_arn', sa.String(length=512), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=32), nullable=True),
    sa.Column('cis_control', sa.String(length=64), nullable=True),
    sa.Column('nist_control', sa.String(length=64), nullable=True),
    sa.Column('mitre_attack', sa.String(length=128), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=False),
    sa.Column('estimated_remediation_time', sa.String(length=64), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('ai_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_session_id'], ['audit_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_audit_session_id'), 'findings', ['audit_session_id'], unique=False)
    op.create_index(op.f('ix_findings_service'), 'findings', ['service'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_session_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('PDF', 'CSV', 'JSON', name='reporttype'), nullable=False),
    sa.Column('category', sa.Enum('EXECUTIVE', 'TECHNICAL', 'COMPLIANCE', 'RISK', 'AUDIT_HISTORY', name='reportcategory'), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_session_id'], ['audit_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_audit_session_id'), 'reports', ['audit_session_id'], unique=False)
    op.create_table('compliance_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('audit_session_id', sa.String(length=36), nullable=False),
    sa.Column('framework', sa.Enum('CIS_AWS_FOUNDATIONS', 'AWS_WELL_ARCHITECTED', 'NIST_CSF', 'ISO_27001', 'SOC_2', name='complianceframework'), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('control_title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PASS', 'WARNING', 'FAIL', name='compliancestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('related_finding_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_session_id'], ['audit_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_results_audit_session_id'), 'compliance_results', ['audit_session_id'], unique=False)
    op.create_index(op.f('ix_compliance_results_framework'), 'compliance_results', ['framework'], unique=False)
    op.create_table('risk_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('finding_id', sa.String(length=36), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('likelihood', sa.Integer(), nullable=False),
    sa.Column('business_impact', sa.Integer(), nullable=False),
    sa.Column('exploitability', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_scores')
    op.drop_index(op.f('ix_compliance_results_framework'), table_name='compliance_results')
    op.drop_index(op.f('ix_compliance_results_audit_session_id'), table_name='compliance_results')
    op.drop_table('compliance_results')
    op.drop_index(op.f('ix_reports_audit_session_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_service'), table_name='findings')
    op.drop_index(op.f('ix_findings_audit_session_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_ai_messages_user_id'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_audit_session_id'), table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_audit_sessions_aws_account_id'), table_name='audit_sessions')
    op.drop_table('audit_sessions')
    op.drop_table('settings')
    op.drop_index(op.f('ix_aws_accounts_user_id'), table_name='aws_accounts')
    op.drop_table('aws_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
